// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBANz4bt6BaxsHV0fHfG2_unLi64E2EPGw',
    appId: '1:899850748940:web:f17f5d9f40a4167283da29',
    messagingSenderId: '899850748940',
    projectId: 'live-score-e553f',
    authDomain: 'live-score-e553f.firebaseapp.com',
    databaseURL: 'https://live-score-e553f-default-rtdb.firebaseio.com',
    storageBucket: 'live-score-e553f.firebasestorage.app',
    measurementId: 'G-XWGVR0YHVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-C3jF3GEO5XbZk9GSa42FfwJsRw4Ylpw',
    appId: '1:899850748940:android:d56d8a94b4bb193983da29',
    messagingSenderId: '899850748940',
    projectId: 'live-score-e553f',
    databaseURL: 'https://live-score-e553f-default-rtdb.firebaseio.com',
    storageBucket: 'live-score-e553f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAW_mK0sqGRwV_tJ0muOCfD9lJGpoUs3g',
    appId: '1:899850748940:ios:95bc1143cff305bf83da29',
    messagingSenderId: '899850748940',
    projectId: 'live-score-e553f',
    databaseURL: 'https://live-score-e553f-default-rtdb.firebaseio.com',
    storageBucket: 'live-score-e553f.firebasestorage.app',
    iosBundleId: 'com.example.crftyBuy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAW_mK0sqGRwV_tJ0muOCfD9lJGpoUs3g',
    appId: '1:899850748940:ios:95bc1143cff305bf83da29',
    messagingSenderId: '899850748940',
    projectId: 'live-score-e553f',
    databaseURL: 'https://live-score-e553f-default-rtdb.firebaseio.com',
    storageBucket: 'live-score-e553f.firebasestorage.app',
    iosBundleId: 'com.example.crftyBuy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBANz4bt6BaxsHV0fHfG2_unLi64E2EPGw',
    appId: '1:899850748940:web:886955c6dce98ad783da29',
    messagingSenderId: '899850748940',
    projectId: 'live-score-e553f',
    authDomain: 'live-score-e553f.firebaseapp.com',
    databaseURL: 'https://live-score-e553f-default-rtdb.firebaseio.com',
    storageBucket: 'live-score-e553f.firebasestorage.app',
    measurementId: 'G-36YVVPEG8E',
  );
}
